In [4]:
import numpy as np
import pandas as pd
from scipy import stats
from scipy.stats import chi2_contingency

In [6]:
data =pd.read_excel("customer_data.xlsx")
data.head(1)

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes

In [8]:
cross_tab =pd.crosstab(data["Purchase_Channel"],data["Region"])
cross_tab

Region            Midwest  Northeast  West
Purchase_Channel
In-store                6          9    12
Online                 21         17    16

In [9]:
chi2,p_value,dof,expected=chi2_contingency(cross_tab)
print("P value  :",p_value)

P value  : 0.2642013027337702

In [10]:
if p_value<0.05:
    print("Reject the null hypothesis")
else:
    print("Fail to reject the null hypothesis")

Fail to reject the null hypothesis