In [56]:
import pandas as pd

In [57]:
data = pd.read_excel("customer_data.xlsx")
data.head()
nan_data = data[data["Customer_Lifespan_Months"].isna()]
print(nan_data)

Empty DataFrame
Columns: [CustomerID, Gender, Age, Income, City, Region, Frequency_of_Purchases, Average_Purchase_Amount, Customer_Lifespan_Months, Purchase_Channel, Date_of_Purchase, Churn_Status]
Index: []

In [58]:
data["Customer_Lifespan_Months"] = pd.to_numeric(data["Customer_Lifespan_Months"], errors='coerce')

In [59]:
data["engagement_level"]=pd.cut(data["Customer_Lifespan_Months"],bins=[0,2,3,5],labels=["Low engaged","Moderately engaged","Highly engaged"],include_lowest=True)

In [60]:
data.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status,engagement_level
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes,Moderately engaged
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,Yes,Highly engaged
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No,Low engaged
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No,Low engaged
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No,Low engaged

In [64]:
mapping={"Low engaged":1,"Moderatly engaged":2,"Highly engaged":3}
data["engagement_level"]=data["engagement_level"].map(mapping)
data.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status,engagement_level
0,C001,Male,49,72504.0,Chicago,Northeast,10,9.824100e+01,3,Online,2022-03-05,Yes,NaN
1,C002,Female,38,40881.0,New York,West,15,1.576400e+02,4,In-store,2023-07-08,Yes,NaN
2,C003,Male,17,63333.0,New York,Northeast,1,4.125200e+01,1,Online,2023-01-30,No,NaN
3,C004,Male,34,58030.0,Chicago,Midwest,6,6.732900e+01,1,In-store,2023-06-01,No,NaN
4,C005,Male,30,78889.0,Houston,Midwest,3,5.276300e+01,1,Online,2022-09-23,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,C076,Male,44,59659.0,Houston,Midwest,14,1.345400e+02,4,Online,2023-12-25,Yes,NaN
76,C077,Female,38,94266.0,Los Angeles,Midwest,5,6.308200e+01,2,Online,2023-01-02,No,NaN
77,C078,Male,30,76887.0,Houston,Midwest,7,8.081600e+01,2,Online,2022-11-14,No,NaN
78,C079,Female,42,56569.0,New York,West,11,1.342341e+07,3,In-store,2022-12-08,Yes,NaN
79,C080,Female,26,43931.0,Los Angeles,Northeast,9,9.153600e+01,2,In-store,2023-09-18,No,NaN

In [62]:
data.isna().sum()

CustomerID                   0
Gender                       0
Age                          0
Income                       5
City                         3
Region                       0
Frequency_of_Purchases       0
Average_Purchase_Amount      0
Customer_Lifespan_Months     0
Purchase_Channel             0
Date_of_Purchase             0
Churn_Status                 0
engagement_level            31
dtype: int64

In [63]:
nan_data = data[data["Customer_Lifespan_Months"].isna()]
print(nan_data)

Empty DataFrame
Columns: [CustomerID, Gender, Age, Income, City, Region, Frequency_of_Purchases, Average_Purchase_Amount, Customer_Lifespan_Months, Purchase_Channel, Date_of_Purchase, Churn_Status, engagement_level]
Index: []