In [1]:
import pandas as pd

In [2]:
data =pd.read_excel("customer_data.xlsx")

In [3]:
data.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,Yes
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No

In [4]:
data.columns

Index(['CustomerID', 'Gender', 'Age', 'Income', 'City', 'Region',
       'Frequency_of_Purchases', 'Average_Purchase_Amount',
       'Customer_Lifespan_Months', 'Purchase_Channel', 'Date_of_Purchase',
       'Churn_Status'],
      dtype='object')

In [10]:
x_reg =data.drop(["CustomerID","Gender","City","Region","Purchase_Channel","Average_Purchase_Amount","Churn_Status"],axis=1)
y_reg =data["Average_Purchase_Amount"]

In [13]:
x_reg

,Age,Income,Frequency_of_Purchases,Customer_Lifespan_Months,Date_of_Purchase
0,49,72504.0,10,3,2022-03-05
1,38,40881.0,15,4,2023-07-08
2,17,63333.0,1,1,2023-01-30
3,34,58030.0,6,1,2023-06-01
4,30,78889.0,3,1,2022-09-23
...,...,...,...,...,...
76,38,94266.0,5,2,2023-01-02
77,30,76887.0,7,2,2022-11-14
78,42,56569.0,11,3,2022-12-08
79,26,43931.0,9,2,2023-09-18
80,22,41743.0,4,1,2023-06-08

In [14]:
x_reg =data.drop(["CustomerID","Gender","City","Region","Purchase_Channel","Average_Purchase_Amount","Churn_Status"],axis=1)
y_reg =data["Churn_Status"]

In [16]:
x_reg
y_reg

0     Yes
1     Yes
2      No
3      No
4      No
     ...
76     No
77     No
78    Yes
79     No
80     No
Name: Churn_Status, Length: 81, dtype: object