In [5]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [2]:
data =pd.read_excel("customer_data.xlsx")
data.head()

,CustomerID,Gender,Age,Income,City,Region,Frequency_of_Purchases,Average_Purchase_Amount,Customer_Lifespan_Months,Purchase_Channel,Date_of_Purchase,Churn_Status
0,C001,Male,49,72504.0,Chicago,Northeast,10,98.241,3,Online,2022-03-05,Yes
1,C002,Female,38,40881.0,New York,West,15,157.640,4,In-store,2023-07-08,Yes
2,C003,Male,17,63333.0,New York,Northeast,1,41.252,1,Online,2023-01-30,No
3,C004,Male,34,58030.0,Chicago,Midwest,6,67.329,1,In-store,2023-06-01,No
4,C005,Male,30,78889.0,Houston,Midwest,3,52.763,1,Online,2022-09-23,No

In [9]:
x_reg =data.drop(["CustomerID","Gender","City","Region","Purchase_Channel","Average_Purchase_Amount","Churn_Status","Date_of_Purchase"],axis=1)
y_reg =data["Average_Purchase_Amount"]

In [10]:
x_reg

    Age   Income  Frequency_of_Purchases  Customer_Lifespan_Months
0    49  72504.0                      10                         3
1    38  40881.0                      15                         4
2    17  63333.0                       1                         1
3    34  58030.0                       6                         1
4    30  78889.0                       3                         1
..  ...      ...                     ...                       ...
76   38  94266.0                       5                         2
77   30  76887.0                       7                         2
78   42  56569.0                      11                         3
79   26  43931.0                       9                         2
80   22  41743.0                       4                         1

[81 rows x 4 columns]

In [11]:
scaler=StandardScaler()
scaled_x_reg=scaler.fit_transform(x_reg)
scaled_x_reg

array([[ 1.37721625e+00,  6.77882186e-01,  2.83578704e-01,
         5.67942908e-01],
       [ 2.96071159e-01, -9.28180519e-01,  1.81490370e+00,
         1.61347417e+00],
       [-1.76793311e+00,  2.12107242e-01, -2.47280630e+00,
        -1.52311962e+00],
       [-9.70725110e-02, -5.72204796e-02, -9.41481296e-01,
        -1.52311962e+00],
       [-4.90216181e-01,  1.00216231e+00, -1.86027630e+00,
        -1.52311962e+00],
       [ 1.67207400e+00,  8.79306614e-01,  5.89843703e-01,
         5.67942908e-01],
       [ 1.21340639e-03,  6.05564364e-02, -2.26862963e-02,
        -4.77588355e-01],
       [ 2.96071159e-01, -1.05413427e+00, -9.41481296e-01,
        -4.77588355e-01],
       [ 8.85786663e-01,  7.08405656e-01,  8.96108703e-01,
         5.67942908e-01],
       [ 1.18064442e+00,  3.14089151e-01,  2.83578704e-01,
         5.67942908e-01],
       [ 1.77035992e+00, -1.58451130e+00,  2.83578704e-01,
         5.67942908e-01],
       [ 6.89214828e-01,  9.78190467e-01, -3.28951296e-01,
        -4.77588355e-01],
       [-1.07993168e+00, -7.08421694e-01,  2.83578704e-01,
         5.67942908e-01],
       [ 2.96071159e-01,  5.74325855e-01,  5.89843703e-01,
         5.67942908e-01],
       [ 8.85786663e-01, -1.35383310e+00, -2.26862963e-02,
         5.67942908e-01],
       [ 1.97785241e-01,  2.91227957e-03,  2.83578704e-01,
         5.67942908e-01],
       [-8.83359850e-01,  8.41520489e-01,  1.20237370e+00,
         1.61347417e+00],
       [ 3.94357076e-01,  1.40038948e+00,  5.89843703e-01,
         5.67942908e-01],
       [-2.93644346e-01, -9.16499325e-01,  1.50863870e+00,
         1.61347417e+00],
       [-6.86788015e-01, -1.12274859e+00, -9.41481296e-01,
        -4.77588355e-01],
       [-1.27650352e+00, -8.84401433e-01, -1.55401130e+00,
        -1.52311962e+00],
       [-8.83359850e-01,  1.00719030e+00, -6.35216296e-01,
        -4.77588355e-01],
       [ 5.90928911e-01,  2.33772918e+00,  1.50863870e+00,
         1.61347417e+00],
       [ 1.86864584e+00, -1.59964607e+00,  8.96108703e-01,
         5.67942908e-01],
       [-7.85073933e-01, -7.06847272e-01,  8.96108703e-01,
         5.67942908e-01],
       [-1.66964719e+00, -1.29385270e+00, -1.24774630e+00,
        -1.52311962e+00],
       [-1.95358428e-01,  4.27955406e-01,  1.50863870e+00,
         1.61347417e+00],
       [-1.95358428e-01,  9.58031719e-02,  2.83578704e-01,
         5.67942908e-01],
       [-4.90216181e-01,  1.80978328e-02,  8.96108703e-01,
         5.67942908e-01],
       [ 1.86864584e+00, -4.30967925e-01,  1.20237370e+00,
         1.61347417e+00],
       [-1.27650352e+00,  1.15980765e+00,  8.96108703e-01,
         5.67942908e-01],
       [-1.37478944e+00, -2.00340509e-01,  8.96108703e-01,
         5.67942908e-01],
       [-3.91930263e-01,  2.00273282e+00, -6.35216296e-01,
        -4.77588355e-01],
       [ 1.77035992e+00,  9.67321877e-01,  8.96108703e-01,
         5.67942908e-01],
       [-6.86788015e-01, -4.63065816e-01, -6.35216296e-01,
        -4.77588355e-01],
       [-1.17821760e+00, -7.96640109e-01, -1.24774630e+00,
        -1.52311962e+00],
       [-9.81645768e-01,  1.24954970e+00, -3.28951296e-01,
        -4.77588355e-01],
       [ 1.86864584e+00,  6.87836596e-01, -2.16654130e+00,
        -1.52311962e+00],
       [ 7.87500746e-01, -3.73679282e-01,  1.50863870e+00,
         1.61347417e+00],
       [ 9.94993238e-02, -1.20192678e+00, -6.35216296e-01,
        -4.77588355e-01],
       [-1.17821760e+00,  6.93016952e-01,  8.96108703e-01,
         5.67942908e-01],
       [ 1.77035992e+00, -3.32185647e-01,  5.89843703e-01,
         5.67942908e-01],
       [ 8.85786663e-01,  3.65029317e-01,  8.96108703e-01,
         5.67942908e-01],
       [ 3.94357076e-01, -1.00771422e+00, -3.28951296e-01,
        -4.77588355e-01],
       [-1.27650352e+00, -6.18476494e-01, -3.28951296e-01,
        -4.77588355e-01],
       [ 8.85786663e-01, -1.34988635e-04,  1.81490370e+00,
         1.61347417e+00],
       [ 8.85786663e-01, -1.14367317e+00,  5.89843703e-01,
         5.67942908e-01],
       [ 1.21340639e-03,  3.64724591e-01, -3.28951296e-01,
        -4.77588355e-01],
       [ 1.37721625e+00, -5.69157528e-02,  8.96108703e-01,
         5.67942908e-01],
       [ 3.94357076e-01, -1.52630848e+00, -6.35216296e-01,
        -4.77588355e-01],
       [-1.57136127e+00, -2.21565133e+00,  2.83578704e-01,
         5.67942908e-01],
       [ 3.94357076e-01, -6.31122658e-01, -9.41481296e-01,
        -1.52311962e+00],
       [ 9.84072580e-01,  1.61014310e+00,  2.83578704e-01,
         5.67942908e-01],
       [-3.91930263e-01, -4.01917301e-01, -6.35216296e-01,
        -4.77588355e-01],
       [-2.93644346e-01, -4.26041508e-01, -1.24774630e+00,
        -1.52311962e+00],
       [-5.88502098e-01,  2.46347978e+00, -1.86027630e+00,
        -1.52311962e+00],
       [-5.88502098e-01, -6.57583103e-01, -2.26862963e-02,
        -4.77588355e-01],
       [-1.66964719e+00, -9.73178513e-01, -6.35216296e-01,
        -4.77588355e-01],
       [ 1.08235850e+00,             nan, -3.28951296e-01,
        -4.77588355e-01],
       [ 1.21340639e-03,  1.18718228e+00, -9.41481296e-01,
        -1.52311962e+00],
       [-1.07993168e+00, -3.08620106e-01,  2.12116870e+00,
         2.65900543e+00],
       [-1.76793311e+00,  1.31760937e-01, -6.35216296e-01,
        -4.77588355e-01],
       [ 3.94357076e-01, -6.10959900e-01,  2.83578704e-01,
         5.67942908e-01],
       [-4.90216181e-01,             nan,  2.83578704e-01,
         5.67942908e-01],
       [-3.91930263e-01, -4.19896183e-01, -2.26862963e-02,
        -4.77588355e-01],
       [ 1.21340639e-03,  8.26741238e-01,  5.89843703e-01,
         5.67942908e-01],
       [ 1.86864584e+00,             nan,  8.96108703e-01,
         5.67942908e-01],
       [ 1.08235850e+00, -1.07896951e+00,  2.83578704e-01,
         5.67942908e-01],
       [-1.17821760e+00, -3.16746155e-01, -2.26862963e-02,
        -4.77588355e-01],
       [ 9.94993238e-02,             nan, -3.28951296e-01,
        -4.77588355e-01],
       [ 9.94993238e-02,  2.24011502e+00,  5.89843703e-01,
         5.67942908e-01],
       [-8.83359850e-01, -2.64938586e-02, -1.24774630e+00,
        -1.52311962e+00],
       [-6.86788015e-01,  7.35120041e-01, -2.26862963e-02,
        -4.77588355e-01],
       [-5.88502098e-01, -7.13703626e-01, -1.24774630e+00,
        -1.52311962e+00],
       [ 6.89214828e-01,             nan, -1.55401130e+00,
        -1.52311962e+00],
       [ 8.85786663e-01,  2.55128521e-02,  1.50863870e+00,
         1.61347417e+00],
       [ 2.96071159e-01,  1.78312636e+00, -1.24774630e+00,
        -4.77588355e-01],
       [-4.90216181e-01,  9.00485128e-01, -6.35216296e-01,
        -4.77588355e-01],
       [ 6.89214828e-01, -1.31421460e-01,  5.89843703e-01,
         5.67942908e-01],
       [-8.83359850e-01, -7.73277719e-01, -2.26862963e-02,
        -4.77588355e-01],
       [-1.27650352e+00, -8.84401433e-01, -1.55401130e+00,
        -1.52311962e+00]])